// Code generated by vexilc. DO NOT EDIT.
// Source: vexmon

import { BitReader, BitWriter } from '@vexil-lang/runtime';

export const SCHEMA_HASH = new Uint8Array([0x11, 0x04, 0x0f, 0x6c, 0x1b, 0x48, 0x52, 0x2c, 0x42, 0xf8, 0x84, 0x75, 0x9f, 0xd8, 0xee, 0x67, 0xfc, 0xec, 0xa0, 0x80, 0xe7, 0x78, 0xc3, 0x8e, 0xbe, 0x93, 0x75, 0xeb, 0x38, 0x52, 0x3e, 0xbe]);

// ── CpuSnapshot ──
export interface CpuSnapshot {
  overall: number;
  per_core: number[];
  frequency: number;
  _unknown: Uint8Array;
}

export function encodeCpuSnapshot(v: CpuSnapshot, w: BitWriter): void {
  w.writeU8(v.overall);
  w.writeLeb128(v.per_core.length);
  for (const item of v.per_core) {
    w.writeU8(item);
  }
  w.writeU16(v.frequency);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeCpuSnapshot(r: BitReader): CpuSnapshot {
  const overall = r.readU8();
  const per_core_len = r.readLeb128();
  const per_core: number[] = [];
  for (let i = 0; i < per_core_len; i++) {
    const per_core_item = r.readU8();
    per_core.push(per_core_item);
  }
  const frequency = r.readU16();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { overall, per_core, frequency, _unknown };
}


// ── MemorySnapshot ──
export interface MemorySnapshot {
  used_bytes: bigint;
  total_bytes: bigint;
  swap_used: bigint;
  swap_total: bigint;
  cached_bytes: bigint;
  _unknown: Uint8Array;
}

export function encodeMemorySnapshot(v: MemorySnapshot, w: BitWriter): void {
  w.writeU64(v.used_bytes);
  w.writeU64(v.total_bytes);
  w.writeU64(v.swap_used);
  w.writeU64(v.swap_total);
  w.writeU64(v.cached_bytes);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeMemorySnapshot(r: BitReader): MemorySnapshot {
  const used_bytes = r.readU64();
  const total_bytes = r.readU64();
  const swap_used = r.readU64();
  const swap_total = r.readU64();
  const cached_bytes = r.readU64();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { used_bytes, total_bytes, swap_used, swap_total, cached_bytes, _unknown };
}


// ── DiskInfo ──
export interface DiskInfo {
  name: string;
  mount: string;
  total_gb: number;
  used_gb: number;
  read_bps: bigint;
  write_bps: bigint;
  _unknown: Uint8Array;
}

export function encodeDiskInfo(v: DiskInfo, w: BitWriter): void {
  w.writeString(v.name);
  w.writeString(v.mount);
  w.writeU32(v.total_gb);
  w.writeU32(v.used_gb);
  w.writeU64(v.read_bps);
  w.writeU64(v.write_bps);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeDiskInfo(r: BitReader): DiskInfo {
  const name = r.readString();
  const mount = r.readString();
  const total_gb = r.readU32();
  const used_gb = r.readU32();
  const read_bps = r.readU64();
  const write_bps = r.readU64();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { name, mount, total_gb, used_gb, read_bps, write_bps, _unknown };
}


// ── NetworkInfo ──
export interface NetworkInfo {
  name: string;
  rx_bps: bigint;
  tx_bps: bigint;
  total_rx: bigint;
  total_tx: bigint;
  _unknown: Uint8Array;
}

export function encodeNetworkInfo(v: NetworkInfo, w: BitWriter): void {
  w.writeString(v.name);
  w.writeU64(v.rx_bps);
  w.writeU64(v.tx_bps);
  w.writeU64(v.total_rx);
  w.writeU64(v.total_tx);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeNetworkInfo(r: BitReader): NetworkInfo {
  const name = r.readString();
  const rx_bps = r.readU64();
  const tx_bps = r.readU64();
  const total_rx = r.readU64();
  const total_tx = r.readU64();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { name, rx_bps, tx_bps, total_rx, total_tx, _unknown };
}


// ── ProcessState ──
export type ProcessState = 'Running' | 'Sleeping' | 'Stopped' | 'Zombie' | 'Unknown';
export const ProcessState = {
  Running: 'Running' as const,
  Sleeping: 'Sleeping' as const,
  Stopped: 'Stopped' as const,
  Zombie: 'Zombie' as const,
  Unknown: 'Unknown' as const,
} as const;

export function encodeProcessState(v: ProcessState, w: BitWriter): void {
  let disc: number;
  switch (v) {
    case 'Running': disc = 0; break;
    case 'Sleeping': disc = 1; break;
    case 'Stopped': disc = 2; break;
    case 'Zombie': disc = 3; break;
    case 'Unknown': disc = 4; break;
    default: throw new Error(`Unknown ProcessState variant: ${v}`);
  }
  w.writeBits(disc, 3);
}

export function decodeProcessState(r: BitReader): ProcessState {
  const disc = r.readBits(3);
  switch (disc) {
    case 0: return 'Running';
    case 1: return 'Sleeping';
    case 2: return 'Stopped';
    case 3: return 'Zombie';
    case 4: return 'Unknown';
    default: throw new Error(`Unknown ProcessState discriminant: ${disc}`);
  }
}


// ── ProcessInfo ──
export interface ProcessInfo {
  pid: number;
  name: string;
  cpu_pct: number;
  mem_mb: number;
  state: ProcessState;
  _unknown: Uint8Array;
}

export function encodeProcessInfo(v: ProcessInfo, w: BitWriter): void {
  w.writeU32(v.pid);
  w.writeString(v.name);
  w.writeU8(v.cpu_pct);
  w.writeU32(v.mem_mb);
  w.enterNested();
  encodeProcessState(v.state, w);
  w.leaveNested();
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeProcessInfo(r: BitReader): ProcessInfo {
  const pid = r.readU32();
  const name = r.readString();
  const cpu_pct = r.readU8();
  const mem_mb = r.readU32();
  r.enterNested();
  const state = decodeProcessState(r);
  r.leaveNested();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { pid, name, cpu_pct, mem_mb, state, _unknown };
}


// ── SystemInfo ──
export interface SystemInfo {
  hostname: string;
  os_name: string;
  os_version: string;
  kernel: string;
  uptime_secs: bigint;
  cpu_brand: string;
  cpu_count: number;
  _unknown: Uint8Array;
}

export function encodeSystemInfo(v: SystemInfo, w: BitWriter): void {
  w.writeString(v.hostname);
  w.writeString(v.os_name);
  w.writeString(v.os_version);
  w.writeString(v.kernel);
  w.writeU64(v.uptime_secs);
  w.writeString(v.cpu_brand);
  w.writeU8(v.cpu_count);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeSystemInfo(r: BitReader): SystemInfo {
  const hostname = r.readString();
  const os_name = r.readString();
  const os_version = r.readString();
  const kernel = r.readString();
  const uptime_secs = r.readU64();
  const cpu_brand = r.readString();
  const cpu_count = r.readU8();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { hostname, os_name, os_version, kernel, uptime_secs, cpu_brand, cpu_count, _unknown };
}


// ── TelemetryFrame ──
export interface TelemetryFrame_Cpu {
  tag: 'Cpu';
  snapshot: CpuSnapshot;
}

export interface TelemetryFrame_Memory {
  tag: 'Memory';
  snapshot: MemorySnapshot;
}

export interface TelemetryFrame_Disks {
  tag: 'Disks';
  disks: DiskInfo[];
}

export interface TelemetryFrame_Network {
  tag: 'Network';
  interfaces: NetworkInfo[];
}

export interface TelemetryFrame_Processes {
  tag: 'Processes';
  top: ProcessInfo[];
}

export interface TelemetryFrame_System {
  tag: 'System';
  info: SystemInfo;
}

export type TelemetryFrame = TelemetryFrame_Cpu | TelemetryFrame_Memory | TelemetryFrame_Disks | TelemetryFrame_Network | TelemetryFrame_Processes | TelemetryFrame_System;

export function encodeTelemetryFrame(v: TelemetryFrame, w: BitWriter): void {
  w.flushToByteBoundary();
  switch (v.tag) {
    case 'Cpu': {
      w.writeLeb128(0);
      const payloadW = new BitWriter();
      payloadW.enterNested();
      encodeCpuSnapshot(v.snapshot, payloadW);
      payloadW.leaveNested();
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(payload.length);
      w.writeRawBytes(payload);
      break;
    }
    case 'Memory': {
      w.writeLeb128(1);
      const payloadW = new BitWriter();
      payloadW.enterNested();
      encodeMemorySnapshot(v.snapshot, payloadW);
      payloadW.leaveNested();
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(payload.length);
      w.writeRawBytes(payload);
      break;
    }
    case 'Disks': {
      w.writeLeb128(2);
      const payloadW = new BitWriter();
      payloadW.writeLeb128(v.disks.length);
      for (const item of v.disks) {
        payloadW.enterNested();
        encodeDiskInfo(item, payloadW);
        payloadW.leaveNested();
      }
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(payload.length);
      w.writeRawBytes(payload);
      break;
    }
    case 'Network': {
      w.writeLeb128(3);
      const payloadW = new BitWriter();
      payloadW.writeLeb128(v.interfaces.length);
      for (const item of v.interfaces) {
        payloadW.enterNested();
        encodeNetworkInfo(item, payloadW);
        payloadW.leaveNested();
      }
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(payload.length);
      w.writeRawBytes(payload);
      break;
    }
    case 'Processes': {
      w.writeLeb128(4);
      const payloadW = new BitWriter();
      payloadW.writeLeb128(v.top.length);
      for (const item of v.top) {
        payloadW.enterNested();
        encodeProcessInfo(item, payloadW);
        payloadW.leaveNested();
      }
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(payload.length);
      w.writeRawBytes(payload);
      break;
    }
    case 'System': {
      w.writeLeb128(5);
      const payloadW = new BitWriter();
      payloadW.enterNested();
      encodeSystemInfo(v.info, payloadW);
      payloadW.leaveNested();
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(payload.length);
      w.writeRawBytes(payload);
      break;
    }
  }
}

export function decodeTelemetryFrame(r: BitReader): TelemetryFrame {
  r.flushToByteBoundary();
  const disc = r.readLeb128();
  const len = r.readLeb128();
  switch (disc) {
    case 0: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      pr.enterNested();
      const snapshot = decodeCpuSnapshot(pr);
      pr.leaveNested();
      pr.flushToByteBoundary();
      return { tag: 'Cpu' as const, snapshot };
    }
    case 1: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      pr.enterNested();
      const snapshot = decodeMemorySnapshot(pr);
      pr.leaveNested();
      pr.flushToByteBoundary();
      return { tag: 'Memory' as const, snapshot };
    }
    case 2: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const disks_len = pr.readLeb128();
      const disks: DiskInfo[] = [];
      for (let i = 0; i < disks_len; i++) {
        pr.enterNested();
        const disks_item = decodeDiskInfo(pr);
        pr.leaveNested();
        disks.push(disks_item);
      }
      pr.flushToByteBoundary();
      return { tag: 'Disks' as const, disks };
    }
    case 3: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const interfaces_len = pr.readLeb128();
      const interfaces: NetworkInfo[] = [];
      for (let i = 0; i < interfaces_len; i++) {
        pr.enterNested();
        const interfaces_item = decodeNetworkInfo(pr);
        pr.leaveNested();
        interfaces.push(interfaces_item);
      }
      pr.flushToByteBoundary();
      return { tag: 'Network' as const, interfaces };
    }
    case 4: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const top_len = pr.readLeb128();
      const top: ProcessInfo[] = [];
      for (let i = 0; i < top_len; i++) {
        pr.enterNested();
        const top_item = decodeProcessInfo(pr);
        pr.leaveNested();
        top.push(top_item);
      }
      pr.flushToByteBoundary();
      return { tag: 'Processes' as const, top };
    }
    case 5: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      pr.enterNested();
      const info = decodeSystemInfo(pr);
      pr.leaveNested();
      pr.flushToByteBoundary();
      return { tag: 'System' as const, info };
    }
    default: {
      throw new Error(`Unknown TelemetryFrame discriminant: ${disc}`);
    }
  }
}

