// Code generated by vexilc. DO NOT EDIT.
// Source: vexmon

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0x87, 0xe7, 0x6c, 0x0b, 0xc2, 0x09, 0x03, 0x0b, 0x0c, 0x2f, 0x0b, 0xd9, 0x1f, 0x2b, 0x1d, 0xf2, 0x30, 0xcd, 0x78, 0x56, 0x0d, 0x48, 0xad, 0x94, 0x92, 0xee, 0xb2, 0x46, 0x32, 0x33, 0x94, 0x27];

// ── CpuSnapshot ──
#[derive(Debug, Clone, PartialEq)]
pub struct CpuSnapshot {
    pub overall: u8,
    pub per_core: Vec<u8>,
    pub frequency: u16,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for CpuSnapshot {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_leb128(self.overall as u64);
        w.write_leb128(self.per_core.len() as u64);
        for item in &self.per_core {
            w.write_u8(*item);
        }
        w.write_leb128(self.frequency as u64);
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for CpuSnapshot {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let overall_raw = r.read_leb128(10_u8)?;
        let overall: u8 = overall_raw as u8;
        let per_core_len = r.read_leb128(10_u8)? as usize;
        let mut per_core = Vec::with_capacity(per_core_len);
        for _ in 0..per_core_len {
            let per_core_item = r.read_u8()?;
            per_core.push(per_core_item);
        }
        let frequency_raw = r.read_leb128(10_u8)?;
        let frequency: u16 = frequency_raw as u16;
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(Self {
            overall,
            per_core,
            frequency,
            _unknown,
        })
    }
}

pub struct CpuSnapshotEncoder {
    prev_overall: u8,
    prev_frequency: u16,
}

impl CpuSnapshotEncoder {
    pub fn new() -> Self {
        Self {
            prev_overall: 0,
            prev_frequency: 0,
        }
    }

    pub fn pack(&mut self, val: &CpuSnapshot, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let delta_overall = val.overall.wrapping_sub(self.prev_overall);
        w.write_leb128(delta_overall as u64);
        self.prev_overall = val.overall;
        w.write_leb128(val.per_core.len() as u64);
        for item in &val.per_core {
            w.write_u8(*item);
        }
        let delta_frequency = val.frequency.wrapping_sub(self.prev_frequency);
        w.write_leb128(delta_frequency as u64);
        self.prev_frequency = val.frequency;
        w.flush_to_byte_boundary();
        if !val._unknown.is_empty() {
            w.write_raw_bytes(&val._unknown);
        }
        Ok(())
    }

    pub fn reset(&mut self) {
        self.prev_overall = 0;
        self.prev_frequency = 0;
    }
}

pub struct CpuSnapshotDecoder {
    prev_overall: u8,
    prev_frequency: u16,
}

impl CpuSnapshotDecoder {
    pub fn new() -> Self {
        Self {
            prev_overall: 0,
            prev_frequency: 0,
        }
    }

    pub fn unpack(&mut self, r: &mut vexil_runtime::BitReader<'_>) -> Result<CpuSnapshot, vexil_runtime::DecodeError> {
        let delta_overall_raw = r.read_leb128(10_u8)?;
        let delta_overall: u8 = delta_overall_raw as u8;
        let overall = self.prev_overall.wrapping_add(delta_overall);
        self.prev_overall = overall;
        let per_core_len = r.read_leb128(10_u8)? as usize;
        let mut per_core = Vec::with_capacity(per_core_len);
        for _ in 0..per_core_len {
            let per_core_item = r.read_u8()?;
            per_core.push(per_core_item);
        }
        let delta_frequency_raw = r.read_leb128(10_u8)?;
        let delta_frequency: u16 = delta_frequency_raw as u16;
        let frequency = self.prev_frequency.wrapping_add(delta_frequency);
        self.prev_frequency = frequency;
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(CpuSnapshot {
            overall,
            per_core,
            frequency,
            _unknown,
        })
    }

    pub fn reset(&mut self) {
        self.prev_overall = 0;
        self.prev_frequency = 0;
    }
}


// ── MemorySnapshot ──
#[derive(Debug, Clone, PartialEq)]
pub struct MemorySnapshot {
    pub used_bytes: u64,
    pub total_bytes: u64,
    pub swap_used: u64,
    pub swap_total: u64,
    pub cached_bytes: u64,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for MemorySnapshot {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_leb128(self.used_bytes as u64);
        w.write_leb128(self.total_bytes as u64);
        w.write_leb128(self.swap_used as u64);
        w.write_leb128(self.swap_total as u64);
        w.write_leb128(self.cached_bytes as u64);
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for MemorySnapshot {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let used_bytes_raw = r.read_leb128(10_u8)?;
        let used_bytes: u64 = used_bytes_raw as u64;
        let total_bytes_raw = r.read_leb128(10_u8)?;
        let total_bytes: u64 = total_bytes_raw as u64;
        let swap_used_raw = r.read_leb128(10_u8)?;
        let swap_used: u64 = swap_used_raw as u64;
        let swap_total_raw = r.read_leb128(10_u8)?;
        let swap_total: u64 = swap_total_raw as u64;
        let cached_bytes_raw = r.read_leb128(10_u8)?;
        let cached_bytes: u64 = cached_bytes_raw as u64;
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(Self {
            used_bytes,
            total_bytes,
            swap_used,
            swap_total,
            cached_bytes,
            _unknown,
        })
    }
}

pub struct MemorySnapshotEncoder {
    prev_used_bytes: u64,
    prev_total_bytes: u64,
    prev_swap_used: u64,
    prev_swap_total: u64,
    prev_cached_bytes: u64,
}

impl MemorySnapshotEncoder {
    pub fn new() -> Self {
        Self {
            prev_used_bytes: 0,
            prev_total_bytes: 0,
            prev_swap_used: 0,
            prev_swap_total: 0,
            prev_cached_bytes: 0,
        }
    }

    pub fn pack(&mut self, val: &MemorySnapshot, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let delta_used_bytes = val.used_bytes.wrapping_sub(self.prev_used_bytes);
        w.write_leb128(delta_used_bytes as u64);
        self.prev_used_bytes = val.used_bytes;
        let delta_total_bytes = val.total_bytes.wrapping_sub(self.prev_total_bytes);
        w.write_leb128(delta_total_bytes as u64);
        self.prev_total_bytes = val.total_bytes;
        let delta_swap_used = val.swap_used.wrapping_sub(self.prev_swap_used);
        w.write_leb128(delta_swap_used as u64);
        self.prev_swap_used = val.swap_used;
        let delta_swap_total = val.swap_total.wrapping_sub(self.prev_swap_total);
        w.write_leb128(delta_swap_total as u64);
        self.prev_swap_total = val.swap_total;
        let delta_cached_bytes = val.cached_bytes.wrapping_sub(self.prev_cached_bytes);
        w.write_leb128(delta_cached_bytes as u64);
        self.prev_cached_bytes = val.cached_bytes;
        w.flush_to_byte_boundary();
        if !val._unknown.is_empty() {
            w.write_raw_bytes(&val._unknown);
        }
        Ok(())
    }

    pub fn reset(&mut self) {
        self.prev_used_bytes = 0;
        self.prev_total_bytes = 0;
        self.prev_swap_used = 0;
        self.prev_swap_total = 0;
        self.prev_cached_bytes = 0;
    }
}

pub struct MemorySnapshotDecoder {
    prev_used_bytes: u64,
    prev_total_bytes: u64,
    prev_swap_used: u64,
    prev_swap_total: u64,
    prev_cached_bytes: u64,
}

impl MemorySnapshotDecoder {
    pub fn new() -> Self {
        Self {
            prev_used_bytes: 0,
            prev_total_bytes: 0,
            prev_swap_used: 0,
            prev_swap_total: 0,
            prev_cached_bytes: 0,
        }
    }

    pub fn unpack(&mut self, r: &mut vexil_runtime::BitReader<'_>) -> Result<MemorySnapshot, vexil_runtime::DecodeError> {
        let delta_used_bytes_raw = r.read_leb128(10_u8)?;
        let delta_used_bytes: u64 = delta_used_bytes_raw as u64;
        let used_bytes = self.prev_used_bytes.wrapping_add(delta_used_bytes);
        self.prev_used_bytes = used_bytes;
        let delta_total_bytes_raw = r.read_leb128(10_u8)?;
        let delta_total_bytes: u64 = delta_total_bytes_raw as u64;
        let total_bytes = self.prev_total_bytes.wrapping_add(delta_total_bytes);
        self.prev_total_bytes = total_bytes;
        let delta_swap_used_raw = r.read_leb128(10_u8)?;
        let delta_swap_used: u64 = delta_swap_used_raw as u64;
        let swap_used = self.prev_swap_used.wrapping_add(delta_swap_used);
        self.prev_swap_used = swap_used;
        let delta_swap_total_raw = r.read_leb128(10_u8)?;
        let delta_swap_total: u64 = delta_swap_total_raw as u64;
        let swap_total = self.prev_swap_total.wrapping_add(delta_swap_total);
        self.prev_swap_total = swap_total;
        let delta_cached_bytes_raw = r.read_leb128(10_u8)?;
        let delta_cached_bytes: u64 = delta_cached_bytes_raw as u64;
        let cached_bytes = self.prev_cached_bytes.wrapping_add(delta_cached_bytes);
        self.prev_cached_bytes = cached_bytes;
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(MemorySnapshot {
            used_bytes,
            total_bytes,
            swap_used,
            swap_total,
            cached_bytes,
            _unknown,
        })
    }

    pub fn reset(&mut self) {
        self.prev_used_bytes = 0;
        self.prev_total_bytes = 0;
        self.prev_swap_used = 0;
        self.prev_swap_total = 0;
        self.prev_cached_bytes = 0;
    }
}


// ── DiskInfo ──
#[derive(Debug, Clone, PartialEq)]
pub struct DiskInfo {
    pub name: String,
    pub mount: String,
    pub total_gb: u32,
    pub used_gb: u32,
    pub read_bps: u64,
    pub write_bps: u64,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for DiskInfo {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_string(&self.name);
        w.write_string(&self.mount);
        w.write_u32(self.total_gb);
        w.write_u32(self.used_gb);
        w.write_u64(self.read_bps);
        w.write_u64(self.write_bps);
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for DiskInfo {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let name = r.read_string()?;
        let mount = r.read_string()?;
        let total_gb = r.read_u32()?;
        let used_gb = r.read_u32()?;
        let read_bps = r.read_u64()?;
        let write_bps = r.read_u64()?;
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(Self {
            name,
            mount,
            total_gb,
            used_gb,
            read_bps,
            write_bps,
            _unknown,
        })
    }
}


// ── NetworkInfo ──
#[derive(Debug, Clone, PartialEq)]
pub struct NetworkInfo {
    pub name: String,
    pub rx_bps: u64,
    pub tx_bps: u64,
    pub total_rx: u64,
    pub total_tx: u64,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for NetworkInfo {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_string(&self.name);
        w.write_u64(self.rx_bps);
        w.write_u64(self.tx_bps);
        w.write_u64(self.total_rx);
        w.write_u64(self.total_tx);
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for NetworkInfo {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let name = r.read_string()?;
        let rx_bps = r.read_u64()?;
        let tx_bps = r.read_u64()?;
        let total_rx = r.read_u64()?;
        let total_tx = r.read_u64()?;
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(Self {
            name,
            rx_bps,
            tx_bps,
            total_rx,
            total_tx,
            _unknown,
        })
    }
}


// ── ProcessState ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum ProcessState {
    Running = 0_u64,
    Sleeping = 1_u64,
    Stopped = 2_u64,
    Zombie = 3_u64,
    Unknown = 4_u64,
}

impl vexil_runtime::Pack for ProcessState {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::Running => 0_u64,
            Self::Sleeping => 1_u64,
            Self::Stopped => 2_u64,
            Self::Zombie => 3_u64,
            Self::Unknown => 4_u64,
        };
        w.write_bits(disc, 3_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for ProcessState {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(3_u8)?;
        match disc {
            0_u64 => Ok(Self::Running),
            1_u64 => Ok(Self::Sleeping),
            2_u64 => Ok(Self::Stopped),
            3_u64 => Ok(Self::Zombie),
            4_u64 => Ok(Self::Unknown),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "ProcessState", value: disc }),
        }
    }
}


// ── ProcessInfo ──
#[derive(Debug, Clone, PartialEq)]
pub struct ProcessInfo {
    pub pid: u32,
    pub name: String,
    pub cpu_pct: u8,
    pub mem_mb: u32,
    pub state: ProcessState,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for ProcessInfo {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u32(self.pid);
        w.write_string(&self.name);
        w.write_u8(self.cpu_pct);
        w.write_u32(self.mem_mb);
        w.enter_recursive()?;
        self.state.pack(w)?;
        w.leave_recursive();
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for ProcessInfo {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let pid = r.read_u32()?;
        let name = r.read_string()?;
        let cpu_pct = r.read_u8()?;
        let mem_mb = r.read_u32()?;
        r.enter_recursive()?;
        let state = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(Self {
            pid,
            name,
            cpu_pct,
            mem_mb,
            state,
            _unknown,
        })
    }
}


// ── SystemInfo ──
#[derive(Debug, Clone, PartialEq)]
pub struct SystemInfo {
    pub hostname: String,
    pub os_name: String,
    pub os_version: String,
    pub kernel: String,
    pub uptime_secs: u64,
    pub cpu_brand: String,
    pub cpu_count: u8,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for SystemInfo {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_string(&self.hostname);
        w.write_string(&self.os_name);
        w.write_string(&self.os_version);
        w.write_string(&self.kernel);
        w.write_u64(self.uptime_secs);
        w.write_string(&self.cpu_brand);
        w.write_u8(self.cpu_count);
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for SystemInfo {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let hostname = r.read_string()?;
        let os_name = r.read_string()?;
        let os_version = r.read_string()?;
        let kernel = r.read_string()?;
        let uptime_secs = r.read_u64()?;
        let cpu_brand = r.read_string()?;
        let cpu_count = r.read_u8()?;
        r.flush_to_byte_boundary();
        let _unknown = r.read_remaining();
        Ok(Self {
            hostname,
            os_name,
            os_version,
            kernel,
            uptime_secs,
            cpu_brand,
            cpu_count,
            _unknown,
        })
    }
}


// ── TelemetryFrame ──
#[derive(Debug, Clone, PartialEq)]
pub enum TelemetryFrame {
    Cpu { snapshot: CpuSnapshot },
    Memory { snapshot: MemorySnapshot },
    Disks { disks: Vec<DiskInfo> },
    Network { interfaces: Vec<NetworkInfo> },
    Processes { top: Vec<ProcessInfo> },
    System { info: SystemInfo },
}

impl vexil_runtime::Pack for TelemetryFrame {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.flush_to_byte_boundary();
        match self {
            Self::Cpu { snapshot } => {
                w.write_leb128(0_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.enter_recursive()?;
                snapshot.pack(&mut payload_w)?;
                payload_w.leave_recursive();
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Memory { snapshot } => {
                w.write_leb128(1_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.enter_recursive()?;
                snapshot.pack(&mut payload_w)?;
                payload_w.leave_recursive();
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Disks { disks } => {
                w.write_leb128(2_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_leb128(disks.len() as u64);
                for item in disks {
                payload_w.enter_recursive()?;
                item.pack(&mut payload_w)?;
                payload_w.leave_recursive();
                }
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Network { interfaces } => {
                w.write_leb128(3_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_leb128(interfaces.len() as u64);
                for item in interfaces {
                payload_w.enter_recursive()?;
                item.pack(&mut payload_w)?;
                payload_w.leave_recursive();
                }
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Processes { top } => {
                w.write_leb128(4_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_leb128(top.len() as u64);
                for item in top {
                payload_w.enter_recursive()?;
                item.pack(&mut payload_w)?;
                payload_w.leave_recursive();
                }
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::System { info } => {
                w.write_leb128(5_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.enter_recursive()?;
                info.pack(&mut payload_w)?;
                payload_w.leave_recursive();
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for TelemetryFrame {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        r.flush_to_byte_boundary();
        let disc = r.read_leb128(10_u8)?;
        let len = r.read_leb128(10_u8)? as usize;
        match disc {
            0_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                pr.enter_recursive()?;
                let snapshot = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                pr.flush_to_byte_boundary();
                Ok(Self::Cpu { snapshot })
            }
            1_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                pr.enter_recursive()?;
                let snapshot = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                pr.flush_to_byte_boundary();
                Ok(Self::Memory { snapshot })
            }
            2_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let disks_len = pr.read_leb128(10_u8)? as usize;
                let mut disks = Vec::with_capacity(disks_len);
                for _ in 0..disks_len {
                pr.enter_recursive()?;
                let disks_item = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                disks.push(disks_item);
                }
                pr.flush_to_byte_boundary();
                Ok(Self::Disks { disks })
            }
            3_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let interfaces_len = pr.read_leb128(10_u8)? as usize;
                let mut interfaces = Vec::with_capacity(interfaces_len);
                for _ in 0..interfaces_len {
                pr.enter_recursive()?;
                let interfaces_item = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                interfaces.push(interfaces_item);
                }
                pr.flush_to_byte_boundary();
                Ok(Self::Network { interfaces })
            }
            4_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let top_len = pr.read_leb128(10_u8)? as usize;
                let mut top = Vec::with_capacity(top_len);
                for _ in 0..top_len {
                pr.enter_recursive()?;
                let top_item = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                top.push(top_item);
                }
                pr.flush_to_byte_boundary();
                Ok(Self::Processes { top })
            }
            5_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                pr.enter_recursive()?;
                let info = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                pr.flush_to_byte_boundary();
                Ok(Self::System { info })
            }
            _ => {
                let _skip = r.read_raw_bytes(len)?;
                Err(vexil_runtime::DecodeError::UnknownUnionVariant { type_name: "TelemetryFrame", discriminant: disc })
            }
        }
    }
}

